server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: poll-service
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

userService:
  url: http://localhost:8080/user-service

